### ISSUE TITLE
BUG: data loss on simultaneous edit of different world objects

### ISSUE THREAD

**Issue by PhyDoesStuff** [Pjb518/FoundryVTT-Level-Up-Official#11]
If two people are editing different Items at the same time, one person will lose their work, while the other will retain their work. It has been observed with the following conditions:

- User 1 is the host and working within the Foundry application, User 2 was accessing Foundry via web browser from another machine
- In cases where User 2 would be renaming an Item attached to an Actor, and User 1 began editing a separate Item, User 2's Item would revert to the default name
    - this applies to cases where User 1 was editing Items attached to the same Actor, and when User 1 was editing Items in the Item Directory
    - this applies when User 1 is doing any editing to their Item (renaming, adding description text, changing details)

I didn't test if this issue also applies to Actors (Actor & Item, Item & Actor, Actor & Actor cases).

**Comment by Pjb518** [comment]
Hey again,

I haven't been able to replicate this so far, but I'm going to do some more testing. It sounds like the issue only occurs in input fields, which makes some sense, because they're the only ones where an update isn't called immediately on click or change. Foundry waits until an input field is unfocused before performing an update.

While waiting for some additional data, I have a plan to make the update listeners for dialogs much more strict about when they refresh the base document data. Hopefully that will fix the issue even if I end up unable to replicate it.

**Comment by Pjb518** [comment]
I realised why this issue was difficult to reproduce. I can open a bunch of Foundry instances on my computer, but if I switch between then, the field I'm concerned with is unfocused immediately. The data is therefore locked in then and there, removing any opportunity for it to be overwritten during another item's edit.

I believe the changes I'm making to the update behaviour will fix this, so let me know if it persists after 0.5.3.

**Comment by PhyDoesStuff** [comment]
That issue seems to be resolved! Thanks for fixing this!

**Comment by Pjb518** [comment]
> That issue seems to be resolved! Thanks for fixing this!

No worries! Glad that it's resolved 🙂
