### ISSUE TITLE
Inompatibility with PopOut!

### ISSUE THREAD

**Issue by Inkemann** [Pjb518/FoundryVTT-Level-Up-Official#18]
The sheets provided by this module are marked as incompatible with the [PopOut!](https://foundryvtt.com/packages/popout) module for FoundryVTT. I removed the `_disable_popout_module` property from the sheets and could not find any incompatibility when testing it. Is there a reason these incompatibility flags have been added?

**Comment by Pjb518** [comment]
Hey,

There are actually _a lot_ of things that don't work when using the system's sheets with PopOut! To give a few of really major examples, the tab navigation and lock button are not functional when the sheet it popped out, and nor are the various roll buttons (for example, for ability checks and saves).

I'm not sure what exactly you tested, because there's very little that functions correctly when the sheets are popped out. If your testing was mostly focused on updating text fields, that stuff works just fine. It's basically everything else which is a problem.

It's not something we can fix on our end, unfortunately. It's a limitation of PopOut!

**Comment by Inkemann** [comment]
The tab navigation and also activating any items or features works perfectly fine in the popped out version for me.

**Comment by Pjb518** [comment]
> The tab navigation and also activating any items or features works perfectly fine in the popped out version for me.

I cannot replicate that in v9 or v10, and this flag was originally added specifically because there were multiple reports of issues like this. Whether or not it works for your particular setup, the widespread issues are reason enough to keep the flag.

**Comment by Pjb518** [comment]
I should also add that these sheets are in the middle of being completely replaced anyway, so whatever flags are present for the current sheets will soon be irrelevant. I don't anticipate the new sheets to play nicely with PopOut! either, however.
