### ISSUE TITLE
[Refactor]: Conver Generic Actor Resource Config to Menu

### ISSUE THREAD

**Issue by NekroDarkmoon** [Pjb518/FoundryVTT-Level-Up-Official#43]
Convert the Dialog configuration of the generic actor resource to use TJSMenu and be inline rather than be a TJSDialog

**Comment by Pjb518** [comment]
@NekroDarkmoon This has been marked as completed, but `0.10.0` doesn't reflect these changes:

<img width="547" alt="image" src="https://user-images.githubusercontent.com/33249712/226832386-2778813c-d974-4605-a50b-e395ef16df77.png">

Given that we're potentially planning to add #114 in some form, this may also not be a desirable change anymore. The drag and drop aspect of that issue may not be viable because of the tab layout, but we can provide select boxes and so on in the resource dialog to allow users to hook up an item to a resource box.
