### ISSUE TITLE
Incompatability with 5e modules

### ISSUE THREAD

**Issue by Ro4m3r** [Pjb518/FoundryVTT-Level-Up-Official#8]
Since this is an entirely new system instead of building on top of 5e, it is incompatible with 5e compendiums as well as pre-created 5e adventures or other community shared content.

Is this intended? It seems very odd for a system that promises "backwards compatibility"...

Edit: I just saw the note in the readme.
For anyone else that cannot read like me: ``Compatibility Note: Level Up is not based on the 5e system implementation in Foundry and 5e-specific modules should not be expected to work.``
Bummer as I depend on too much 5e specific content to switch to this. I guess I will attempt to whip something up that works for my own needs. Cheers.

**Comment by Pjb518** [comment]
Hey,

Regarding the promise of "backward compatibility", what was actually promised was that the game would be backwards compatible with the 5th edition ruleset. There was absolutely no promise that there would be backwards compatibility with a specific software implementation of the system and any other specific software implementation of the 5th edition system.

That being said, there are plans in place to provide migration options as part of the Level Up Foundry system, so that 5e Foundry content can be automatically converted to work in Level Up. I certainly don't intend to leave users completely in the lurch with regards to all of their existing 5e content.

In addition to this, there's nothing stopping community members from developing importer tools specific to Level Up once the system is more mature, drawing content from other VTTs or D&D Beyond. Even at this very early stage, there's been plenty of interest in Level Up module development, and several dedicated modules have already been released. Some popular modules have also added specific support for the system where necessary.

Regarding the decision to create a wholly new system, this was not taken lightly or decided on a whim. The reason we opted to take this approach is because it was actually simpler, and we believe we can provide something better than what the 5e system on Foundry currently offers. The goal is to provide a much richer feature set as part of the Level Up system, making many of the modules that 5e players rely on completely unnecessary.

Hopefully that answers your questions 🙂

**Comment by Ro4m3r** [comment]
Sounds promising! I wish you the best of luck and if more of these features make it in I may consider a swap.

If nothing else from the short look I took the character sheets and general UI looked much cleaner than the default foundry look, so very well done on that front.
